#!/usr/bin/env bash

for link in *; do
    if [[ -L ~/.${link##*/} ]]; then
        echo OK: $link 
    elif [[ -e ~/.${link##*/} ]]; then
        echo NOK: $link
    else
        echo NEW: $link
        ln -s `pwd`/$link ~/.${link##*/}
    fi
done

ln -s `pwd`/Library/Preferences/com.googlecode.iterm2.plist ~/Library/Preferences/com.googlecode.iterm2.plist || true
ln -s ~/.vim ~/.config/nvim || true

rm ~/.make-links ~/.README.md
