#!/bin/bash

components='
ack
bash
bin
fontconfig
fonts
git
i3
mac
screen
scripts
ssh
term
tmux
udev
vim
zsh
oh-my-zsh'

mkdir -p ~/.config ~/.Library

for c in $components ; do
	stow --verbose 1 -R -t $HOME $c
done
