#!/bin/bash

set -x
set -e 

displays_off() {
    DISPLAYS=$(xrandr | grep ' connected ' | awk '{print $1}')

    for i in $DISPLAYS ; do 
        xrandr --output $i --off
    done
}

displays_off
sleep 0.1

CONFIGURATION=$1
case $CONFIGURATION in 
    home)
        xrandr --output eDP-1 --mode 1920x1080
        xrandr --output HDMI-1 --mode 1920x1080 --right-of eDP-1 --primary
        ;;
    mendix)
        xrandr --output eDP1 --mode 1920x1080
        xrandr --output DP2-2 --mode 1920x1080 --right-of eDP1
        xrandr --output DP2-1 --mode 1920x1080 --right-of DP2-2 --primary
        ;;
    *)
        xrandr --output eDP1 --auto --primary
        xrandr --auto
        ;;
esac

feh --bg-scale ~/Pictures/wallpaper.jpg || true
i3-msg restart
